### ISSUE TITLE
Timeout problem when wrong cdn is selected

### ISSUE THREAD

**Issue by AliM1988** [CodeWithEmad/apyrat#4] opened 2024-01-11 14:16 UTC
* Apyrat version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

Example: https://www.aparat.com/playlist/8175010
It is the output:
echo "480p" | apyrat https://www.aparat.com/playlist/8175010
Loading playlist videos
Enter the quality you want to download (144p, 240p, 360p, 480p, 720p) [720p]: آموزش برنامه نویسی پایتون استاد جادی قسمت 17
https://caspian13.cdn.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-480p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjU2MDE2ZjczZGZkNTdlM2MyNTMxYWI4NjU5ZDJlMWViIiwiZXhwIjoxNzA1MDAwMDExLCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.e_PvQPsHZMOOBGBf8qWbx5OUyEOyx7HPtw6M2iFbaLA
...
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

----------------------------------------------------------
actually the url (https://caspian13.cdn.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-480p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjU2MDE2ZjczZGZkNTdlM2MyNTMxYWI4NjU5ZDJlMWViIiwiZXhwIjoxNzA1MDAwMDExLCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.e_PvQPsHZMOOBGBf8qWbx5OUyEOyx7HPtw6M2iFbaLA) is not responded. for this case correct cdn is hajifirouz3 -> ([https://hajifirouz3 .cdn.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-480p.mp4](https://hajifirouz3.cdn.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-480p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjA2NWZkM2ExM2Q4ZDI4MDI0MzU0OGJiYjU1NTk5YzA2IiwiZXhwIjoxNzA1MDAwMDc3LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.KaVdegaSkREFmGMZlmKZGTg8IsCOdE1qCLofDhvfxm8))

**Comment by CodeWithEmad** [comment] 2024-01-13 05:42
Thank you for your time. would you like to open a PR?

**Comment by CodeWithEmad** [comment] 2024-02-25 19:40
Well, aparat API returns something like this: 
```python
.
.
    [
        {
            "title": "آموزش برنامه نویسی پایتون استاد جادی قسمت 17",
            "profile": "144p",
            "url": "https://persian11.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-144p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImViOWM2NGMyMzFlZThkNmI5MjU2NjZkYzVmYzQzZDJkIiwiZXhwIjoxNzA4OTA3NTY4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.AWGXa469yPlRj9mUFfSIVm6yHCxEuPIJFQllZ-D0E3k",
        },
        {
            "title": "آموزش برنامه نویسی پایتون استاد جادی قسمت 17",
            "profile": "240p",
            "url": "https://persian11.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-240p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImViOWM2NGMyMzFlZThkNmI5MjU2NjZkYzVmYzQzZDJkIiwiZXhwIjoxNzA4OTA3NTY4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.AWGXa469yPlRj9mUFfSIVm6yHCxEuPIJFQllZ-D0E3k",
        },
        {
            "title": "آموزش برنامه نویسی پایتون استاد جادی قسمت 17",
            "profile": "360p",
            "url": "https://persian11.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-360p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImViOWM2NGMyMzFlZThkNmI5MjU2NjZkYzVmYzQzZDJkIiwiZXhwIjoxNzA4OTA3NTY4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.AWGXa469yPlRj9mUFfSIVm6yHCxEuPIJFQllZ-D0E3k",
        },
        {
            "title": "آموزش برنامه نویسی پایتون استاد جادی قسمت 17",
            "profile": "480p",
            "url": "https://persian11.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-480p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImViOWM2NGMyMzFlZThkNmI5MjU2NjZkYzVmYzQzZDJkIiwiZXhwIjoxNzA4OTA3NTY4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.AWGXa469yPlRj9mUFfSIVm6yHCxEuPIJFQllZ-D0E3k",
        },
        {
            "title": "آموزش برنامه نویسی پایتون استاد جادی قسمت 17",
            "profile": "720p",
            "url": "https://persian11.asset.aparat.com/aparat-video/194f2de337a9a894f24cf426d8ae665756183216-720p.mp4?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImViOWM2NGMyMzFlZThkNmI5MjU2NjZkYzVmYzQzZDJkIiwiZXhwIjoxNzA4OTA3NTY4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.AWGXa469yPlRj9mUFfSIVm6yHCxEuPIJFQllZ-D0E3k",
        },
    ],
.
.
```
each time you request to download a video or playlist and the script uses these URLs to download the video. 
The links were probably updated then (a little bad luck?). Anyway, I couldn't reproduce that issue, so I'll close it.

**Closed as completed by CodeWithEmad** 2024-02-25 19:40 UTC
